name: lmiis
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.11+12

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_framework: ^0.2.0
  flutter_svg:
  
 
  google_fonts: ^4.0.4
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  open_file_safe: ^3.2.3
  dio: ^5.3.0
  get_storage: ^2.1.1
  get_it: ^7.6.0
  file_picker: ^4.6.1
  intl: ^0.18.1
  flutter_html: ^2.2.1
  image_picker: ^1.0.1

  multiselect_formfield: ^0.1.7
  flutter_riverpod: ^2.3.6
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  loading_gifs: ^0.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0  

  flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter:

  uses-material-design: true


  assets:
    - assets/image/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: uniform
      fonts:
        - asset: assets/font/Uniform_Condensed.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
